export const GET_TICKER_REQUEST = "GET_TICKER_REQUEST";
export const GET_TICKER_SUCCESS = "GET_TICKER_SUCCESS";
export const GET_TICKER_FAILURE = "GET_TICKER_FAILURE";

export const SET_BTC_TICKER = "SET_BTC_TICKER";
export const SET_INITIALIZE_TRADES = "SET_INITIALIZE_TRADES";
export const SET_TRADES = "SET_TRADES";
export const SET_INITIALIZE_ORDERBOOK = "SET_INITIALIZE_ORDERBOOK";
export const SET_ORDERBOOK = "SET_ORDERBOOK";
